version: '3'
services:
  collectd-installer:
    build: ./../collectd-installer
    container_name: collectd-installer
    environment:
      - USER=$USER
      - PASS=$PASS
      - OS=$OS
      - MODE=$MODE
    network_mode: host
  model-repository:
    build: ./../model-repository
    container_name: model-repository
    ports:
      - 5000:5000
    networks:
      - net
    volumes:
      - models:/mlflow
    extra_hosts:
      - model-repository:127.0.0.1
  smart-optimizer:
    build: ./../smart-optimizer
    container_name: smart-optimizer
    environment:
      - MODE=$MODE
    networks:
      - net
  smart-predictor:
    build: ./../smart-predictor
    container_name: smart-predictor
    ports:
      - 9106:9106
    networks:
      - net
  collectd-exporter:
    build: ./../collectd-exporter
    container_name: collectd-exporter
    ports:
      - 9103:9103
    networks:
      - net
  baidu-exporter:
    build: ./../data-exporter/baidu
    container_name: baidu-exporter
    networks:
      - net
  backblaze-exporter:
    build: ./../data-exporter/backblaze
    container_name: backblaze-exporter
    networks:
      - net
  test-exporter:
    build: ./../data-exporter/test
    container_name: test-exporter
    networks:
      - net
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    networks:
      - net
    volumes:
      - ./prometheus:/etc/prometheus
      - tsdb:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - net
    volumes:
    - dashboard:/var/lib/grafana
networks:
  net:
volumes:
  tsdb:
    external: false
  models:
    external: false
  dashboard:
    external: false